@BASE_URL=http://localhost:3000/api

###
POST {{BASE_URL}}/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email":"santiago@google.com",
  "password": "santiago123"
}

###
POST {{BASE_URL}}/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email":"santiago@google.com",
  "password": "santiago123"
}

###
GET {{BASE_URL}}/auth/currentuser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2M2YzAzNzlhZDY0M2MxZWM1MDk1ZjEiLCJpYXQiOjE2NzM5NzI3NDEsImV4cCI6MTY3Mzk3OTk0MX0.Zs5K2GYeVmQAUwhnqE5x16wdlTcO0t7vmr3yLb-JaFk

###
GET {{BASE_URL}}/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2M2YzAzNzlhZDY0M2MxZWM1MDk1ZjEiLCJpYXQiOjE2NzM5NzI3NDEsImV4cCI6MTY3Mzk3OTk0MX0.Zs5K2GYeVmQAUwhnqE5x16wdlTcO0t7vmr3yLb-JaFk

###
GET {{BASE_URL}}/users/63c6c0379ad643c1ec HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2M2YzAzNzlhZDY0M2MxZWM1MDk1ZjEiLCJpYXQiOjE2NzM5NzI3NDEsImV4cCI6MTY3Mzk3OTk0MX0.Zs5K2GYeVmQAUwhnqE5x16wdlTcO0t7vmr3yLb-JaFk